Framework
Yurasb/url_shortener_testing pull request #6
Opened 2018-06-17 09:28 UTC by Yurasb

PR for comments

2018-06-20 14:43 UTC, v1-wizard requested changes

2018-06-20 14:43 UTC, v1-wizard commented on tests/test_delete_all_links.py
> +        dict(code=dict(type='integer', allowed=[200]), body=dict(empty=True))
Не стоит везде использовать везде dict(...). Зачем? Тут у тебя структура является JSON'ом и читать её с {} в разы проще.

2018-06-20 14:43 UTC, v1-wizard commented on tests/test_delete_all_links.py
> +        dict(code=dict(type='integer', allowed=[200]), body=dict(empty=True))
И так везде. Вообще, всегда оценивай насколько будет легко этот код потом понимать стороннему человеку.

2018-06-20 14:43 UTC, v1-wizard commented on data/http_config.yml
> +host: 'localhost'
Зачем тебе нужно несколько файлов конфигов? Если у тебя не 9000 строк конфига, то лучше сделать один файл, чтобы человек зайдя в него смог получить полную информацию о том, что можно настроить или изменить.

2018-06-20 14:43 UTC, v1-wizard commented on data/schemas.yml
> +TC1:
Если уже выносишь тесты в какой-то файлик, то тогда уже пиши в этих файлах человеческим языком и вю необходимую инфомрацию для поинмания тесте ложи рядом. А то у тебя схемы в одном месте, тестовые данные в другом. Представь, как ты будет править или справлять тесты постоянно пригая в IDE между файлами. И, я если честно, не смотря в код не смогу понять, как мне добавить ещё один тест.

2018-06-20 14:43 UTC, v1-wizard commented on data/schemas.yml
> +TC1:
Вообще, я бы так делать не стал. Лучше уж кодом написать всё. И так, чтобы всё сразу было видно в тесте.

2018-06-20 14:43 UTC, v1-wizard commented on data/data_provider.py
> +    def provide_config_for(protocol):
Зачем тебе нужно класс, если все методы static? DataProvider.provide_config_for(...) - вообще, провайдер провайдит - ну такое.

2018-06-20 14:43 UTC, v1-wizard commented on tests/test_delete_all_links.py
> +    ws_connection.send(json.dumps(
json.dumsp(  можно спрятать внутрь метода.

2018-06-20 14:43 UTC, v1-wizard commented on tests/test_shortcut.py
> +    actual_response = client.create_shortcut(test_context)
Если ты оборачиваешь клиент в свою оберточку, то можешь так же обернуть и респонс, чтобы что код, что респонс можно было одинаково получать как из http, так и из ws ответа.

2018-06-20 14:43 UTC, v1-wizard commented on tests/test_shortcut.py
> +    actual_response = client.create_shortcut(test_context)
Тогда тесты будут полностью абстрагированы от протокола.

2018-06-20 14:43 UTC, v1-wizard commented on logic/validation.py
> +    def _matches(self, item):
А в чём у тебя была проблема с матчерами?

2018-06-20 14:43 UTC, v1-wizard commented on tests/test_shortcut.py
> +    actual_response = client.create_shortcut(test_context)
И можно будет всё собрать в один матчер.

2018-06-20 14:43 UTC, v1-wizard commented on tests/test_shortcut.py
> +    actual_response = client.create_shortcut(test_context)
Идеальный тест должен быть в две строчки. =)

2018-06-20 14:43 UTC, v1-wizard commented on tests/conftest.py
> +def http_client(request):
Тебе не надо переконфигуривать клиент, так что я бы сделал его инициализацию, максимально статичным. Можно даже без фикстур. И даже без объекта клиента. Сделать синглтоном конфиги и все эти методы клиентов сделать методами модуля. К примеру.

2018-06-24 10:06 UTC, Yurasb commented on data/http_config.yml
> +host: 'localhost'
Done

2018-06-24 10:07 UTC, Yurasb commented on data/schemas.yml
> +TC1:
Надо обсудить реализацию

2018-06-24 10:12 UTC, Yurasb commented on data/data_provider.py
> +    def provide_config_for(protocol):
Done

2018-06-24 10:13 UTC, Yurasb commented on tests/test_shortcut.py
> +    actual_response = client.create_shortcut(test_context)
Нужно обсудить реализацию

2018-06-24 10:14 UTC, Yurasb commented on logic/validation.py
> +    def _matches(self, item):
Матчер не работал если возвращать кортеж

2018-06-24 10:18 UTC, Yurasb commented on tests/conftest.py
> +def http_client(request):
Нужно обсудить реализацию

2018-06-24 10:20 UTC, Yurasb commented on tests/test_delete_all_links.py
> +        dict(code=dict(type='integer', allowed=[200]), body=dict(empty=True))
Да, это будет убрано по мере переписывания тестов.

2018-06-24 10:20 UTC, Yurasb commented on tests/test_delete_all_links.py
> +    ws_connection.send(json.dumps(
Будет убрано по мере переписывания тестов.

2018-06-26 22:46 UTC, Yurasb commented on tests/conftest.py
> +def http_client(request):
Done

2018-07-01 16:16 UTC, Yurasb commented on tests/test_shortcut.py
> +    actual_response = client.create_shortcut(test_context)
Вопрос в читабельности тестов. Раздельные проверки на код ответа и тело имхо лучше чем одна проверка по схеме, потому что нагляднее.

2018-07-01 16:56 UTC, Yurasb commented on data/schemas.yml
> +TC1:
Пока вынес в модуль data константами.

2018-07-03 22:40 UTC, closed without merging